/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package list.insertions;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        LinkedList<Integer> newLinkedList = new LinkedList();
//        newLinkedList.AddToHead(5);
//        newLinkedList.AddToHead(2);
//        newLinkedList.AddToHead(10);
//        newLinkedList.Append(20);
//        newLinkedList.InsertBefore(3,5);
//        newLinkedList.InsertBefore(2,20);
//        newLinkedList.InsertBefore(20,100);
//        newLinkedList.InsertAfter(20,100);

        newLinkedList.AddToHead(8);
        newLinkedList.Append(6);
        newLinkedList.Append(7);
        newLinkedList.InsertAfter(7,10);

        System.out.println(newLinkedList.ToString());
        System.out.println(newLinkedList.ValueExist(10));
        newLinkedList.PrintElements();
    }
}
