/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.data.Vertex;
import graph.structure.Graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        Graph<String> graph2 = new Graph<>();
        graph2.addNode("A");
        graph2.addNode("B");
        graph2.addNode("C");
        graph2.addNode("D");
        graph2.addEdge(new Vertex<>("A"),new Vertex<>("B"));
        graph2.addEdge(new Vertex<>("A"),new Vertex<>("C"));
        graph2.addEdge(new Vertex<>("B"),new Vertex<>("C"));
        graph2.addEdge(new Vertex<>("B"),new Vertex<>("A"));
        graph2.addEdge(new Vertex<>("B"),new Vertex<>("D"));
        graph2.addEdge(new Vertex<>("C"),new Vertex<>("D"));
        graph2.addEdge(new Vertex<>("C"),new Vertex<>("A"));
        graph2.addEdge(new Vertex<>("C"),new Vertex<>("B"));
        graph2.addEdge(new Vertex<>("D"),new Vertex<>("C"));
        graph2.addEdge(new Vertex<>("D"),new Vertex<>("B"));
       // System.out.println(graph2.breadthFirst("A"));


        Graph<String> graph = new Graph<>();
        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");
        graph.addNode("Naboo");

        graph.addEdge(new Vertex<>("Pandora"),new Vertex<>("Arendelle"));

        graph.addEdge(new Vertex<>("Arendelle"),new Vertex<>("Metroville"));
        graph.addEdge(new Vertex<>("Arendelle"),new Vertex<>("Monstroplolis"));
        graph.addEdge(new Vertex<>("Arendelle"),new Vertex<>("pan"));

        graph.addEdge(new Vertex<>("Metroville"),new Vertex<>("aren"));
        graph.addEdge(new Vertex<>("Metroville"),new Vertex<>("Monstroplolis"));
        graph.addEdge(new Vertex<>("Metroville"),new Vertex<>("Narnia"));
        graph.addEdge(new Vertex<>("Metroville"),new Vertex<>("Naboo"));

        graph.addEdge(new Vertex<>("Narnia"),new Vertex<>("Metroville"));
        graph.addEdge(new Vertex<>("Narnia"),new Vertex<>("Naboo"));

        graph.addEdge(new Vertex<>("Monstroplolis"),new Vertex<>("Arendelle"));
        graph.addEdge(new Vertex<>("Monstroplolis"),new Vertex<>("Metroville"));
        graph.addEdge(new Vertex<>("Monstroplolis"),new Vertex<>("Naboo"));

        graph.addEdge(new Vertex<>("Naboo"),new Vertex<>("Monstroplolis"));
        graph.addEdge(new Vertex<>("Naboo"),new Vertex<>("Metroville"));
        graph.addEdge(new Vertex<>("Naboo"),new Vertex<>("Narnia"));
        System.out.println(graph.breadthFirst("Pandora"));

    }
}
