/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.data.Vertex;
import graph.structure.Graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph<String> graph = new Graph<>();

        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");

        graph.addEdge(new Vertex<>("A"),new Vertex<>("B"),1);
        graph.addEdge(new Vertex<>("B"),new Vertex<>("C"),2);

        System.out.println("The Nodes => "+graph.getNodes());
        System.out.println("*************");
        System.out.println("The Neighbors for A => "+graph.getNeighbors(new Vertex<>("A")));
        System.out.println("The Neighbors for B => "+graph.getNeighbors(new Vertex<>("B")));
        System.out.println("The Neighbors for C => "+graph.getNeighbors(new Vertex<>("C")));
        System.out.println("The Neighbors for D => "+graph.getNeighbors(new Vertex<>("D")));
        System.out.println("*************");

        System.out.println("The size of the graph => "+graph.size());
        System.out.println("*************");

        System.out.println("The Graph => "+graph.printGraph());

        System.out.println("//////////////////////////////");
        Graph<String> graph2 = new Graph<>();
        graph2.addNode("pan");
        graph2.addNode("aren");
        graph2.addNode("met");
        graph2.addNode("mons");
        graph2.addNode("nab");
        graph2.addNode("nar");

        graph2.addEdge(new Vertex<>("pan"),new Vertex<>("aren"));

        graph2.addEdge(new Vertex<>("aren"),new Vertex<>("met"));
        graph2.addEdge(new Vertex<>("aren"),new Vertex<>("mons"));
        graph2.addEdge(new Vertex<>("aren"),new Vertex<>("pan"));

        graph2.addEdge(new Vertex<>("met"),new Vertex<>("aren"));
        graph2.addEdge(new Vertex<>("met"),new Vertex<>("mons"));
        graph2.addEdge(new Vertex<>("met"),new Vertex<>("nar"));
        graph2.addEdge(new Vertex<>("met"),new Vertex<>("nab"));

        graph2.addEdge(new Vertex<>("nar"),new Vertex<>("met"));
        graph2.addEdge(new Vertex<>("nar"),new Vertex<>("nab"));

        graph2.addEdge(new Vertex<>("mons"),new Vertex<>("aren"));
        graph2.addEdge(new Vertex<>("mons"),new Vertex<>("met"));
        graph2.addEdge(new Vertex<>("mons"),new Vertex<>("nab"));

        graph2.addEdge(new Vertex<>("nab"),new Vertex<>("mons"));
        graph2.addEdge(new Vertex<>("nab"),new Vertex<>("met"));
        graph2.addEdge(new Vertex<>("nab"),new Vertex<>("nar"));

        //System.out.println(graph2.BFS(graph2,"pan"));


    }
}
