/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package treeMax;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println(" /////////////// Binary Search Tree ///////////////");
        BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
        binarySearchTree.add(100);
        binarySearchTree.add(2);
        binarySearchTree.add(20);
        binarySearchTree.add(200);
        binarySearchTree.add(400);
        System.out.println(binarySearchTree);
        System.out.println("Pre Order Array => "+binarySearchTree.PreOrder());
        System.out.println("The Maximum value in the tree => "+binarySearchTree.Max_Value());
    }

}
