/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.depth.first;

import graph.depth.first.data.Vertex;
import graph.depth.first.structure.Graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph<String> graph = new Graph<>();
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");
        graph.addNode("E");
        graph.addNode("F");
        graph.addNode("G");
        graph.addNode("H");
        graph.addEdge(new Vertex<>("A"),new Vertex<>("D"));
        graph.addEdge(new Vertex<>("A"),new Vertex<>("B"));

        graph.addEdge(new Vertex<>("B"),new Vertex<>("A"));
        graph.addEdge(new Vertex<>("B"),new Vertex<>("D"));
        graph.addEdge(new Vertex<>("B"),new Vertex<>("C"));

        graph.addEdge(new Vertex<>("C"),new Vertex<>("B"));
        graph.addEdge(new Vertex<>("C"),new Vertex<>("G"));

        graph.addEdge(new Vertex<>("D"),new Vertex<>("A"));
        graph.addEdge(new Vertex<>("D"),new Vertex<>("B"));
        graph.addEdge(new Vertex<>("D"),new Vertex<>("E"));
        graph.addEdge(new Vertex<>("D"),new Vertex<>("H"));
        graph.addEdge(new Vertex<>("D"),new Vertex<>("F"));

        graph.addEdge(new Vertex<>("E"),new Vertex<>("D"));

        graph.addEdge(new Vertex<>("F"),new Vertex<>("D"));
        graph.addEdge(new Vertex<>("F"),new Vertex<>("H"));

        graph.addEdge(new Vertex<>("G"),new Vertex<>("C"));

        graph.addEdge(new Vertex<>("H"),new Vertex<>("F"));
        graph.addEdge(new Vertex<>("H"),new Vertex<>("D"));

         System.out.println(graph.DepthFirst(new Vertex<>("A")));
    }
}
