/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Quick_Sort;

import org.junit.jupiter.api.Test;

import static Quick_Sort.App.QuickSort;
import static org.junit.jupiter.api.Assertions.*;
class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void TestMergeSort(){
        int[] arrayList = new int[]{ 8,4,23,42,16,15 };
        QuickSort(arrayList,0,5);
        int[] result = new int[]{4,8,15,16,23,42};
        assertArrayEquals(result,arrayList);
    }
}
