/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.data.Vertex;
import graph.structure.Graph;
import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void BFS(){
        Graph<String> graph2 = new Graph<>();
        graph2.addNode("A");
        graph2.addNode("B");
        graph2.addNode("C");
        graph2.addNode("D");
        graph2.addEdge(new Vertex<>("A"),new Vertex<>("B"));
        graph2.addEdge(new Vertex<>("A"),new Vertex<>("C"));
        graph2.addEdge(new Vertex<>("B"),new Vertex<>("C"));
        graph2.addEdge(new Vertex<>("B"),new Vertex<>("A"));
        graph2.addEdge(new Vertex<>("B"),new Vertex<>("D"));
        graph2.addEdge(new Vertex<>("C"),new Vertex<>("D"));
        graph2.addEdge(new Vertex<>("C"),new Vertex<>("A"));
        graph2.addEdge(new Vertex<>("C"),new Vertex<>("B"));
        graph2.addEdge(new Vertex<>("D"),new Vertex<>("C"));
        graph2.addEdge(new Vertex<>("D"),new Vertex<>("B"));
        Set<String> result = graph2.breadthFirst("A");
        Set<String> expected = new HashSet<>();
        expected.add("A");
        expected.add("B");
        expected.add("C");
        expected.add("D");

        assertEquals(expected,result);
    }
}
