/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import org.junit.jupiter.api.Test;

import static hashmap.repeated.word.App.repeatedWord;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void noRepeated(){
        String str = "Welcome to Java";
        String result = repeatedWord(str);
        assertEquals("Not has duplicate",result);
    }

    @Test void Repeated(){
        String str = "Once upon a time, there was a brave princess who...";
        String result = repeatedWord(str);
        assertEquals("a",result);
    }

    @Test void RepeatedWithChar(){
        String str = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        String result = repeatedWord(str);
        assertEquals("summer",result);
    }
}
