/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap_Left_Join;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;

import static hashmap_Left_Join.App.hashmap_left_join;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void left_join(){
        HashMap<String,String> hashMap1 = new HashMap<>();
        HashMap<String,String> hashMap2 = new HashMap<>();

        hashMap1.put("diligent","employed");
        hashMap1.put("outfit","garb");
        hashMap1.put("wrath","anger");

        hashMap2.put("diligent","idle");
        hashMap2.put("flow","jam");
        hashMap2.put("wrath","delight");

        ArrayList<ArrayList<String>> arrayList = new ArrayList<>();
        arrayList = hashmap_left_join(hashMap1,hashMap2);
        ArrayList<ArrayList<String>> expected = new ArrayList<>();
        ArrayList<String> arrayList1 = new ArrayList<>();
        arrayList1.add("diligent");
        arrayList1.add("employed");
        arrayList1.add("idle");
        ArrayList<String> arrayList2 = new ArrayList<>();
        arrayList2.add("outfit");
        arrayList2.add("garb");
        arrayList2.add("NULL");
        ArrayList<String> arrayList3 = new ArrayList<>();
        arrayList3.add("wrath");
        arrayList3.add("anger");
        arrayList3.add("delight");

        expected.add(arrayList1);
        expected.add(arrayList2);
        expected.add(arrayList3);
        assertArrayEquals(expected.toArray(),arrayList.toArray());
    }
}
