/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import hashtable.structure.HashTable;

import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        HashTable<String, String> hashTable = new HashTable<String,String>();
        hashTable.set("JAVA", "JAVA Value");
        hashTable.set("Amman", "Amman Value");
        // No duplicate keys => Only Replace the value
        hashTable.set("Amman", "Amman 2 Value");
        hashTable.set("Jordan", "Jordan Value");
        hashTable.set("J", "J Value");
        hashTable.set("Bob", "Bob Value");
        hashTable.set("Carl", "Carl Value");
        System.out.println("///////////// Get the Value ///////////////");
        System.out.println("JAVA => "+hashTable.get("JAVA"));
        System.out.println("Amman => "+hashTable.get("Amman"));
        System.out.println("Jordan => "+hashTable.get("Jordan"));
        System.out.println("J => "+hashTable.get("J"));
        System.out.println("Bob => "+hashTable.get("Bob"));
        System.out.println("Carl => "+hashTable.get("Carl"));
        System.out.println("/////////// Contains Method //////////////");
        System.out.println("java => "+hashTable.contains("java"));
        System.out.println("Amman => "+hashTable.contains("Amman"));
        System.out.println("jordan => "+hashTable.contains("jordan"));
        System.out.println("J => "+hashTable.contains("J"));
        System.out.println("Bob => "+hashTable.contains("Bob"));
        System.out.println("Carl => "+hashTable.contains("Carl"));
        System.out.println("//////////// Keys Collection//////////////");
        System.out.println(hashTable.keys());
        System.out.println("//////////// get the Index ///////////////");
        System.out.println("JAVA => "+hashTable.hash("JAVA"));
        System.out.println("Amman => "+hashTable.hash("Amman"));
        System.out.println("Jordan => "+hashTable.hash("Jordan"));
        System.out.println("J => "+hashTable.hash("J"));
        System.out.println("Bob => "+hashTable.hash("Bob"));
        System.out.println("Carl => "+hashTable.hash("Carl"));
    }
}
