/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[] intArray = new int[]{ 20,18,12,8,5,-2 };
        System.out.println(Arrays.toString(insertionSort(intArray)));
        System.out.println("///////////////////");
        int[] intArray2 = new int[]{ 5,12,7,5,5,7 };
        System.out.println(Arrays.toString(insertionSort(intArray2)));
        System.out.println("///////////////////");
        int[] intArray3 = new int[]{ 2,3,5,7,13,11 };
        System.out.println(Arrays.toString(insertionSort(intArray3)));
        System.out.println("///////////////////");
    }

    public static int[] insertionSort(int[] arr){
        for (int i = 1; i < arr.length; i++) {
            int j = i-1;
            int temp = arr[i];

            while (j>=0 && temp< arr[j])
            {
                arr[j+1] = arr[j];
                j = j-1;

            }

            arr[j+1] = temp;
        }
        return arr;
    }
}
