/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package list.kth;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LinkedList<String> linkedList = new LinkedList<>();
//        linkedList.Append(10);
//        linkedList.Append(2);
//        linkedList.Append(2);
//        linkedList.Append(3);
//        linkedList.Append(2);
//        linkedList.Append(10);

        linkedList.Append("h");
        linkedList.Append("o");
        linkedList.Append("u");
        linkedList.Append("s");
        linkedList.Append("e");

        System.out.println(linkedList.ToString());
        System.out.println("Index 0 value => "+linkedList.kthFromEnd(0));
        System.out.println("Index 2 value => "+linkedList.kthFromEnd(2));
       // System.out.println(linkedList.kthFromEnd(6)); // this will throw an exception
        System.out.println("The Middle value => "+linkedList.TheMiddlevalue());

        linkedList.reverseLinkedList1(linkedList.head);
        System.out.println(linkedList.ToString());
        // System.out.println(linkedList.LinkedListLength());
        linkedList.CopyLinkedList(linkedList.head);
        System.out.println(linkedList.ToString());
        System.out.println(linkedList.isPalindrome(linkedList.head));
    }
}
