/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        PseudoQueue<Integer> pseudoQueue = new PseudoQueue<>();
        pseudoQueue.enqueue(20);
        pseudoQueue.enqueue(15);
        pseudoQueue.enqueue(10);
        pseudoQueue.enqueue(5);
        System.out.println("/////////////////////// ");
        System.out.println(pseudoQueue);
        System.out.println("/////////////////////// ");
        System.out.println( "Remove => "+ pseudoQueue.dequeue());
        System.out.println(pseudoQueue);
        System.out.println("/////////////////////// ");
        System.out.println( "Remove => "+ pseudoQueue.dequeue());
        System.out.println(pseudoQueue);
    }
}
