/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testInsertionSort(){
        int[] intArray = new int[]{ 20,18,12,8,5,-2 };
        int[] result = insertionSort(intArray);
        int[] expected = new int[]{ -2,5,8,12,18,20 };

        assertArrayEquals(expected,result);
    }

    public static int[] insertionSort(int[] arr){
        for (int i = 1; i < arr.length; i++) {
            int j = i-1;
            int temp = arr[i];
            while (j>=0 && temp< arr[j])
            {
                arr[j+1] = arr[j];
                j = j-1;
            }
            arr[j+1] = temp;
        }
        return arr;
    }
}
