/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animal.shelter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        animalSelter animalSelter = new animalSelter();

        Cat cat1 = new Cat("1");
        Cat cat2 = new Cat("2");
        Dog dog1 =new Dog("1");
        Dog dog2 =new Dog("2");
        Dog dog3 =new Dog("3");

        animalSelter.enqueue(dog1);
        animalSelter.enqueue(dog2);
        animalSelter.enqueue(dog3);
        animalSelter.enqueue(cat1);
        animalSelter.enqueue(cat2);
        System.out.println(animalSelter);

        System.out.println("Remove Dog From shelter => "+animalSelter.dequeue("dog"));
        System.out.println("Remove Cat From shelter => "+animalSelter.dequeue("cat"));
        System.out.println("Remove Not Cat or Dog From shelter => "+animalSelter.dequeue("bird"));

        System.out.println(animalSelter);
    }
}
