/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap_Left_Join;
import org.checkerframework.checker.units.qual.A;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Objects;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        HashMap<String,String> hashMap1 = new HashMap<>();
        HashMap<String,String> hashMap2 = new HashMap<>();

        hashMap1.put("diligent","employed");
        hashMap1.put("font","enamored");
        hashMap1.put("guide","usher");
        hashMap1.put("outfit","garb");
        hashMap1.put("wrath","anger");

        hashMap2.put("diligent","idle");
        hashMap2.put("font","averse");
        hashMap2.put("guide","follow");
        hashMap2.put("flow","jam");
        hashMap2.put("wrath","delight");

        System.out.println(hashmap_left_join(hashMap1,hashMap2));
    }

    public static ArrayList<ArrayList<String>> hashmap_left_join(HashMap<String,String> hashMap1 ,
                                                                 HashMap<String,String> hashMap2) {
        ArrayList<ArrayList<String>> arrayResult = new ArrayList<>();
        ArrayList<String> arrayList = new ArrayList<>();
        for (String key :
                hashMap1.keySet()) {
                if (hashMap2.containsKey(key)) {
                    arrayList.add(key);
                    arrayList.add(hashMap1.get(key));
                    arrayList.add(hashMap2.get(key));
                } else {
                     arrayList.add(key);
                     arrayList.add(hashMap1.get(key));
                     arrayList.add("NULL");
                    }
            arrayResult.add(arrayList);
            arrayList = new ArrayList<>();
                }
        return arrayResult;
    }


}
