/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package list.zip;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        LinkedList<Integer> linkedList1 = new LinkedList<>();
        LinkedList<Integer>  linkedList2 = new LinkedList<>();
        linkedList1.AddToHead(1);
        linkedList1.Append(3);
        linkedList1.Append(5);
        linkedList1.Append(3);
        linkedList1.Append(5);

        System.out.println(linkedList1.ToString());
        linkedList2.AddToHead(2);
        linkedList2.Append(4);
        linkedList2.Append(6);
        linkedList2.Append(7);

        System.out.println(linkedList2.ToString());


        System.out.println(linkedList1.LinkedListZip(linkedList1,linkedList2).ToString());

    }
}
