/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizz.buzz;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinaryTree<Integer> binaryTree = new BinaryTree<>();
        binaryTree.setRoot(new Node<>(10));

        binaryTree.getRoot().setLeftNode(new Node<>(5));
        binaryTree.getRoot().setRightNode(new Node<>(15));

        binaryTree.getRoot().getLeftNode().setLeftNode(new Node<>(25));
        binaryTree.getRoot().getLeftNode().setRightNode(new Node<>(6));

        binaryTree.getRoot().getRightNode().setLeftNode(new Node<>(2));
        binaryTree.getRoot().getRightNode().setRightNode(new Node<>(4));

        System.out.println("The origin Tree => "+binaryTree.PreOrder());
        System.out.println(("The Result Tree => "+binaryTree.fizzBuzz(binaryTree).PreOrder()));
    }
}
