/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

import org.junit.jupiter.api.Test;

import java.util.EmptyStackException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    PseudoQueue<Integer> pseudoQueue = new PseudoQueue<>();
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void Testenqueue(){
        pseudoQueue.enqueue(1);
        assertTrue(pseudoQueue.getStackIn().peek().equals(1));
    }
    @Test void TestMultienqueue(){
        pseudoQueue.enqueue(1);
        pseudoQueue.enqueue(2);

        assertTrue(pseudoQueue.getStackIn().peek().equals(2));
    }
  @Test void TestEmptydequeue(){
        try {
            pseudoQueue.dequeue();
            fail("Must throw Exception");
        }catch (EmptyStackException e){
        }
  }
  @Test void Testdequeue(){
      pseudoQueue.enqueue(1);
      pseudoQueue.enqueue(2);
      Integer remove = pseudoQueue.dequeue();
    assertTrue(remove.equals(1));
  }
}
