/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Merge_Sort;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int[] arrayList = new int[]{ 8,4,23,42,16,15 };
        System.out.println(Arrays.toString(arrayList));
        mergeSort(arrayList);
        System.out.println(Arrays.toString(arrayList));
        System.out.println("/////////////////");
        int[] arrayList2 = new int[]{ 20,18,12,8,5,-2 };
        System.out.println(Arrays.toString(arrayList2));
        mergeSort(arrayList2);
        System.out.println(Arrays.toString(arrayList2));
        System.out.println("/////////////////");
        int[] arrayList3 = new int[]{ 5,12,7,5,5,7 };
        System.out.println(Arrays.toString(arrayList3));
        mergeSort(arrayList3);
        System.out.println(Arrays.toString(arrayList3));
        System.out.println("/////////////////");
        int[] arrayList4 = new int[]{ 2,3,5,7,13,11 };
        System.out.println(Arrays.toString(arrayList4));
        mergeSort(arrayList4);
        System.out.println(Arrays.toString(arrayList4));
        System.out.println("/////////////////");

    }
    public static void mergeSort(int[] arr){
        int n = arr.length;
        if(n>1){
            int mid = n/2;
            int[] leftArray = new int[mid];
            for (int i = 0; i < leftArray.length; i++) {
                leftArray[i] = arr[i];
            }
            int[] rightArray = new int[n-mid];
            for (int j = 0; j < rightArray.length ; j++) {
                rightArray[j] = arr[mid+j];
            }
//            System.out.println(Arrays.toString(leftArray));
//            System.out.println(Arrays.toString(rightArray));
//            System.out.println("/////");
            mergeSort(leftArray);
            mergeSort(rightArray);
            merge(leftArray,rightArray,arr);
        }
    }
    public static void merge(int[] leftArray , int[] rightArray , int[] arr){
        //System.out.println("merge");
        int i=0;
        int j=0;
        int k=0;
        while( i < leftArray.length && j < rightArray.length) {
            if (leftArray[i] <= rightArray[j]) {
                arr[k] = leftArray[i];
                i++;
            } else {
                arr[k] = rightArray[j];
                j++;
            }
            k++;
        }

        if(i == leftArray.length){
            while ( j < rightArray.length){
                arr[k] = rightArray[j];
                j++;
                k++;
            }
        }
        if( j == rightArray.length){
            while ( i < leftArray.length){
                arr[k] = leftArray[i];
                i++;
                k++;
            }
        }
//        System.out.println(Arrays.toString(leftArray));
//        System.out.println(Arrays.toString(rightArray));
//        System.out.println(Arrays.toString(arr));
//        System.out.println("End merge");

    }
}
