/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package validate_brackets;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Must be True => "+validate_brackets("{}{Code}[Fellows](())"));
        System.out.println("Must be True => "+validate_brackets("{}(){}"));
        System.out.println("Must be False => "+validate_brackets("()}"));
        System.out.println("Must be False => "+validate_brackets("{(})"));


    }

    public static Boolean validate_brackets(String string) {
        if (string.length() == 0){
            throw new IllegalArgumentException();
        }
        Stack<Character> stack_open = new Stack<>();
        for (int i = 0; i < string.length(); i++) {
            if (string.charAt(i) == '{' || string.charAt(i) == '(' || string.charAt(i) == '[') {
                stack_open.push(string.charAt(i));
            }else{
                // It works string = "()}" // It is close bracket but it doesn't have open bracket
                if(stack_open.isEmpty()){
                    return false;
                }
                if(string.charAt(i) !='}' && string.charAt(i)!=')' && string.charAt(i)!=']'  ){
                    continue;
                }else {
                    if (string.charAt(i) == '}' && stack_open.peek() != '{')
                        return false;
                     if (string.charAt(i) == ')' && stack_open.peek() != '(')
                        return false;
                     if (string.charAt(i) == ']' && stack_open.peek() != '[')
                        return false;

                     stack_open.pop(); // if the open bracket has the close bracket
                }
            }
        }
        // if the stack still not empty that means open bracket doesn't have close bracket
        if(!stack_open.isEmpty()){
            return false;
        }
        return true;
    }
}
